DELETE http://localhost:3001/api/blogs/68bf83f47e56626d3da725cb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyYWQiLCJpZCI6IjY4YmY3YWY3NDNlMGRhY2M0NDIwZDRiYyIsImlhdCI6MTc1NzM4MjE0OH0.yJITQVooISgyUkqDyaXntsjuOhNGrEWbJot3TZs4T4c